liip_imagine:
    driver: "imagick"

    default_filter_set_settings:
        format: webp
        quality: 85

    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: /media/cache

    filter_sets:
        cache: ~
        admin_thumb:
            quality: 85
            filters:
                thumbnail: { size: [120, 90], mode: outbound }

        listing_thumb:
            quality: 85
            filters:
                thumbnail: { size: [400, 300], mode: inset }

        big:
            quality: 90
            filters:
                thumbnail: { size: [1024, 768], mode: inset }
