sonata_media:
    db_driver: doctrine_orm
    default_context: default
    contexts:
        default:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.youtube
                - sonata.media.provider.file
                - sonata.media.provider.vimeo
            formats:
                admin_thumb: { width: 120, height: 90, quality: 85 }
                listing_thumb: { width: 400, quality: 85 }
                big: { width: 1024, quality: 90 }

    cdn:
        server:
            path: /uploads/media

    filesystem:
        local:
            directory: "%kernel.project_dir%/public/uploads/media"
            create: true

    providers:
        image:
            resizer: App\Resizer\LiipImagineResizer

